apiVersion: v1
kind: Service
metadata:
  name: cloud-native-api
  namespace: cloud-native
  labels:
    app: cloud-native-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: cloud-native-api